# check list of acknowledgments and assistants

```{r}
authors_lead <- read_csv("data/lead_authors.csv")

data_contributors <- 
  austraits$contributors %>% 
  mutate(
    acknowledge = ifelse(
      # old studies or excluded
      dataset_id %in% c("Westman_1977", "Hall_1981", "Hocking_1982", "Kuo_1982", "Hocking_1986", "Toelken_1996", "Brock_1993", "Forster_1992", "Forster_1995", "Goble_1981") |
        role %in% c("assistant")
        , TRUE, FALSE),
    year = dataset_id %>% str_split_fixed("_", 4) %>% .[,2]) %>% 
  arrange(year) %>%
  # take most recent address for each author
  group_by(name) %>% 
  summarise(institution = last(institution),
            dataset_ids = paste(dataset_id, collapse = ", "),
            acknowledge = all(acknowledge)) %>% 
  ungroup() %>% 
  distinct() %>% 
  mutate(surname = str_split(name, " ") %>% map_chr(last)) %>% 
  rename(affiliation = institution) %>%
  arrange(surname) %>% 
  select(-surname)

authors <- bind_rows(authors_lead %>% mutate(acknowledge=FALSE), 
                     data_contributors %>% filter(! (name %in% authors_lead$name))
  ) %>% 
  rename(affiliation_dataset = affiliation)
```

```{r}
affiliations_sheet <- 
  googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1nYE5V7utbExcfGmsfILjoXdVsEMDi5CLF_H-uE57EOo/edit#gid=280623389") %>% 
  filter(!is.na(name))

responses_sheet <- 
  googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1UJKSb5YMzIMTmEd-PIqgHwxpSkCEHMJN_gf0r1vTmxU/edit#gid=499607997") %>% 
  rename(name = `Name as shown on paper`)

```

Mark acknowledgments

```{r}
authors2 <- 
  authors %>% 
  mutate(
    #known 
    acknowledge = ifelse(name %in% (affiliations_sheet %>% filter(status != "author") %>% pull(name)), TRUE, acknowledge)
  )

# Check who hasn't responded
authors2 %>% filter(!acknowledge, !(name %in% responses_sheet$name)) %>% pull(name)


authors3 <- 
  authors2 %>% 
  mutate(
    # no response
    acknowledge = ifelse(!(name %in% responses_sheet$name), TRUE, acknowledge)
  )

# Save acknowledgments
authors3 %>% filter(acknowledge) %>% select(name, dataset_ids) %>% write_csv("data/acknowledge_list.csv")

authors4 <- 
  authors3 %>% 
  filter(!acknowledge) %>%
  left_join(by="name", affiliations_sheet %>% select(name, email, affiliation))  %>%
  left_join(by="name",
    responses_sheet %>% 
    select(name, 
            corrected_name = `If you answered no to above, please provide a corrected name`,
            corrected_affiliation = `If you answered no to above, please provide a corrected affiliation`,
            preferred_email = `Preferred email address you would like us to use?  (one only please)`,
            orcid = `Please provide your ORCID id, if you have one.` 
            ) %>%
    mutate(orcid = orcid %>% str_remove_all("[https]+://")  %>% str_remove_all("orcid.org/") )
    ) %>%
  mutate(
    name = ifelse(!is.na(corrected_name), corrected_name, name),
    affiliation = ifelse(!is.na(corrected_affiliation), corrected_affiliation, affiliation),
    email = ifelse(!is.na(preferred_email), preferred_email, email)
  )

authors4 %>% select (name, affiliation, orcid) %>% 
write_csv("data/author_list.csv")

authors4 %>% select (name, affiliation, email, orcid) %>% 
write_csv("data/author_list_email.csv")

```



```{r}
authors4 %>% pull(email) %>% paste(collapse= ", ") %>% clipr::write_clip()
authors %>% pull(name)
```
